local:
  selenium_url: "http://localhost:4444/wd/hub"
  appium_url: "http://localhost:4723/wd/hub"

docker:
  selenium_url: "http://selenium:4444/wd/hub"
  appium_url: "http://appium:4723/wd/hub"

staging:
  selenium_url: "http://grid.company.com:4444/wd/hub"
  appium_url: "http://appium.company.com:4723/wd/hub"